const WEIGHT_CLASSES = [
  {
    id: 'flyweight', icon: '⚡',
    label: 'FLYWEIGHT', limit: '125 lb / 56.7 kg',
    champ: { name:'td7 (1 def)', flag:'🏳️', record:'Win' },
    fighters: [
      { rank:1, name:'td0', flag:'🏳️', record:'Loss' },
      { rank:2, name:'td3', flag:'🏳️', record:'Win' },
      { rank:3, name:'td0', flag:'🏳️', record:'Loss' },
      { rank:4, name:'td0', flag:'🏳️', record:'Loss' },
      { rank:5, name:'td5', flag:'🏳️', record:'Win' },
      { rank:6, name:'td1', flag:'🏳️', record:'Win' },
      { rank:7, name:'td0', flag:'🏳️', record:'Loss' },
      { rank:8, name:'td2', flag:'🏳️', record:'Win' },
      { rank:9, name:'td0', flag:'🏳️', record:'Loss' },
      { rank:10, name:'td2', flag:'🏳️', record:'Win' },
      { rank:11, name:'td0', flag:'🏳️', record:'NC' },
      { rank:12, name:'21–14–1', flag:'🏳️', record:'td0' },
      { rank:13, name:'td0', flag:'🏳️', record:'Loss' },
      { rank:14, name:'td1', flag:'🏳️', record:'Win' },
    ]
  },
  {
    id: 'bantamweight', icon: '🥊',
    label: 'BANTAMWEIGHT', limit: '135 lb / 61.2 kg',
    champ: { name:'td4 (0 def)', flag:'🏳️', record:'Win' },
    fighters: [
      { rank:1, name:'td0', flag:'🏳️', record:'Loss' },
      { rank:2, name:'+1 td2', flag:'🏳️', record:'Win' },
      { rank:3, name:'−1 td2', flag:'🏳️', record:'Win' },
      { rank:4, name:'td0', flag:'🏳️', record:'Loss' },
      { rank:5, name:'td1', flag:'🏳️', record:'Win' },
      { rank:6, name:'td0', flag:'🏳️', record:'Loss' },
      { rank:7, name:'td1', flag:'🏳️', record:'Win' },
      { rank:8, name:'td10', flag:'🏳️', record:'Win' },
      { rank:9, name:'td0', flag:'🏳️', record:'Loss' },
      { rank:10, name:'23–12–1', flag:'🏳️', record:'td0' },
      { rank:11, name:'td2', flag:'🏳️', record:'Win' },
      { rank:12, name:'td0', flag:'🏳️', record:'Loss' },
      { rank:13, name:'td5', flag:'🏳️', record:'Win' },
      { rank:14, name:'td5', flag:'🏳️', record:'Win' },
    ]
  },
  {
    id: 'featherweight', icon: '🦅',
    label: 'FEATHERWEIGHT', limit: '145 lb / 65.8 kg',
    champ: { name:'td2 (1 def)', flag:'🏳️', record:'Win' },
    fighters: [
      { rank:1, name:'td20', flag:'🏳️', record:'Win' },
      { rank:2, name:'td1', flag:'🏳️', record:'Win' },
      { rank:3, name:'td0', flag:'🏳️', record:'Loss' },
      { rank:4, name:'td2', flag:'🏳️', record:'Win' },
      { rank:5, name:'td1', flag:'🏳️', record:'Win' },
      { rank:6, name:'td1', flag:'🏳️', record:'Win' },
      { rank:7, name:'td1', flag:'🏳️', record:'Win' },
      { rank:8, name:'td0', flag:'🏳️', record:'Loss' },
      { rank:9, name:'+1 td7', flag:'🏳️', record:'Win' },
      { rank:10, name:'−1 td0', flag:'🏳️', record:'Loss' },
      { rank:11, name:'td0', flag:'🏳️', record:'Loss' },
      { rank:12, name:'td1', flag:'🏳️', record:'Win' },
      { rank:13, name:'td0', flag:'🏳️', record:'Loss' },
      { rank:14, name:'td0', flag:'🏳️', record:'Loss' },
    ]
  },
  {
    id: 'lightweight', icon: '💨',
    label: 'LIGHTWEIGHT', limit: '155 lb / 70.3 kg',
    champ: { name:'+1 td3 (0 def)', flag:'🏳️', record:'Win' },
    fighters: [
      { rank:1, name:'−1 td0', flag:'🏳️', record:'Loss' },
      { rank:2, name:'td5', flag:'🏳️', record:'Win' },
      { rank:3, name:'td2', flag:'🏳️', record:'Win' },
      { rank:4, name:'td0', flag:'🏳️', record:'Loss' },
      { rank:5, name:'td4', flag:'🏳️', record:'Win' },
      { rank:6, name:'td0', flag:'🏳️', record:'Loss' },
      { rank:7, name:'+2 td2', flag:'🏳️', record:'Win' },
      { rank:8, name:'−1 td1', flag:'🏳️', record:'Win' },
      { rank:9, name:'−1 td0', flag:'🏳️', record:'Loss' },
      { rank:10, name:'−1 td1', flag:'🏳️', record:'Win' },
      { rank:11, name:'td0', flag:'🏳️', record:'Loss' },
      { rank:12, name:'td12', flag:'🏳️', record:'Win' },
      { rank:13, name:'+1 td0', flag:'🏳️', record:'Loss' },
      { rank:14, name:'+1 td5', flag:'🏳️', record:'Win' },
    ]
  },
  {
    id: 'welterweight', icon: '💪',
    label: 'WELTERWEIGHT', limit: '170 lb / 77.1 kg',
    champ: { name:'td16 (0 def)', flag:'🏳️', record:'Win' },
    fighters: [
      { rank:1, name:'td2', flag:'🏳️', record:'Win' },
      { rank:2, name:'td3', flag:'🏳️', record:'Win' },
      { rank:3, name:'td19', flag:'🏳️', record:'Win' },
      { rank:4, name:'td0', flag:'🏳️', record:'Loss' },
      { rank:5, name:'td5', flag:'🏳️', record:'Win' },
      { rank:6, name:'td1', flag:'🏳️', record:'Win' },
      { rank:7, name:'td0', flag:'🏳️', record:'Loss' },
      { rank:8, name:'td0', flag:'🏳️', record:'Loss' },
      { rank:9, name:'td1', flag:'🏳️', record:'Win' },
      { rank:10, name:'td0', flag:'🏳️', record:'Loss' },
      { rank:11, name:'td3', flag:'🏳️', record:'Win' },
      { rank:12, name:'td4', flag:'🏳️', record:'Win' },
      { rank:13, name:'td3', flag:'🏳️', record:'Win' },
      { rank:14, name:'td3', flag:'🏳️', record:'Win' },
    ]
  },
  {
    id: 'middleweight', icon: '🔥',
    label: 'MIDDLEWEIGHT', limit: '185 lb / 83.9 kg',
    champ: { name:'td2 (0 def)', flag:'🏳️', record:'Win' },
    fighters: [
      { rank:1, name:'td0', flag:'🏳️', record:'Loss' },
      { rank:2, name:'td0', flag:'🏳️', record:'Loss' },
      { rank:3, name:'td5', flag:'🏳️', record:'Win' },
      { rank:4, name:'td3', flag:'🏳️', record:'Win' },
      { rank:5, name:'td1', flag:'🏳️', record:'Win' },
      { rank:6, name:'td0', flag:'🏳️', record:'Loss' },
      { rank:7, name:'td4', flag:'🏳️', record:'Win' },
      { rank:8, name:'td0', flag:'🏳️', record:'Loss' },
      { rank:9, name:'td0', flag:'🏳️', record:'Loss' },
      { rank:10, name:'td0', flag:'🏳️', record:'Loss' },
      { rank:11, name:'td0', flag:'🏳️', record:'Loss' },
      { rank:12, name:'td3', flag:'🏳️', record:'Win' },
      { rank:13, name:'td4', flag:'🏳️', record:'Win' },
      { rank:14, name:'td0', flag:'🏳️', record:'Loss' },
    ]
  },
  {
    id: 'lightheavyweight', icon: '🦁',
    label: 'LIGHT HEAVYWEIGHT', limit: '205 lb / 92.9 kg',
    champ: { name:'td10 (0 def)', flag:'🏳️', record:'Win' },
    fighters: [
      { rank:1, name:'td0', flag:'🏳️', record:'Loss' },
      { rank:2, name:'td0', flag:'🏳️', record:'Loss' },
      { rank:3, name:'td0', flag:'🏳️', record:'Loss' },
      { rank:4, name:'29–11–2', flag:'🏳️', record:'td0' },
      { rank:5, name:'td0', flag:'🏳️', record:'Loss' },
      { rank:6, name:'td0', flag:'🏳️', record:'Loss' },
      { rank:7, name:'td2', flag:'🏳️', record:'Win' },
      { rank:8, name:'td0', flag:'🏳️', record:'Loss' },
      { rank:9, name:'td1', flag:'🏳️', record:'Win' },
      { rank:10, name:'td0', flag:'🏳️', record:'Draw' },
      { rank:11, name:'td1', flag:'🏳️', record:'Win' },
      { rank:12, name:'td1', flag:'🏳️', record:'Win' },
      { rank:13, name:'td0', flag:'🏳️', record:'Loss' },
      { rank:14, name:'td0', flag:'🏳️', record:'Loss' },
    ]
  },
  {
    id: 'heavyweight', icon: '🏔️',
    label: 'HEAVYWEIGHT', limit: '265 lb / 120.2 kg',
    champ: { name:'td0 (0 def)', flag:'🏳️', record:'@mediascreen{html.skin-theme-clientpref-night.mw-parser-outputdiv:not(.notheme)>.tmp-color,html.skin-theme-clientpref-night.mw-parser-outputp>.tmp-color,html.skin-theme-clientpref-night.mw-parser-outputtable:not(.notheme).tmp-color{color:inherit!important}}@mediascreenand(prefers-color-scheme:dark){html.skin-theme-clientpref-os.mw-parser-outputdiv:not(.notheme)>.tmp-color,html.skin-theme-clientpref-os.mw-parser-outputp>.tmp-color,html.skin-theme-clientpref-os.mw-parser-outputtable:not(.notheme).tmp-color{color:inherit!important}}NC' },
    fighters: [
      { rank:2, name:'td2', flag:'🏳️', record:'Win' },
      { rank:3, name:'td3', flag:'🏳️', record:'Win' },
      { rank:4, name:'+1 td10', flag:'🏳️', record:'Win' },
      { rank:5, name:'−1 td0', flag:'🏳️', record:'Loss' },
      { rank:6, name:'td1', flag:'🏳️', record:'Win' },
      { rank:7, name:'td0', flag:'🏳️', record:'Loss' },
      { rank:8, name:'td1', flag:'🏳️', record:'Win' },
      { rank:9, name:'+1 td4', flag:'🏳️', record:'Win' },
      { rank:10, name:'+1 td0', flag:'🏳️', record:'Loss' },
      { rank:11, name:'−2 td0', flag:'🏳️', record:'Loss' },
      { rank:12, name:'td0', flag:'🏳️', record:'Loss' },
      { rank:13, name:'td4', flag:'🏳️', record:'Win' },
      { rank:14, name:'td3', flag:'🏳️', record:'Win' },
    ]
  },
];
