import { Fighter, WeightClass } from './types';

export const LANG: Record<string, Record<string, string>> = {
  en: {
    title: "P4P Fan Rankings",
    subtitle: "Pound for Pound · Fan Rankings",
    statVotes: "Fan Votes", statPi: "Pi Collected", statPts: "Points / 1π",
    p4pSec: "Men's P4P · Fan Vote Leaderboard",
    voteFor: "Vote For", voteCost: "Vote Cost", toFighter: "To Fighter",
    walletNote: "1 Pi is sent to the organizer's Pi wallet:",
    confirmVote: "CONFIRM VOTE — 1π",
    champion: "CHAMPION", tabP4P: "🏆 P4P TOP-15",
    toastSuccess: "Vote counted for", toastPts: "+100 pts",
    toastError: "Payment cancelled or failed. Please try again.",
    pts: "pts", loading: "PROCESSING…",
    disclaimer: "This app is a fan project and is not affiliated with, endorsed, or sponsored by any professional sports organization.",
    p4pOfficialRank: "Official rank",
    votesPrefix: "Votes:",
    sandboxDemo: "Sandbox Demo",
    piBrowser: "Pi Browser",
    piExclusive: "Pi Network Exclusive",
    limit: "Limit",
    contender: "Division Contender",
    ranking: "Ranking",
    vote: "Vote",
    dualchamp: "Dual Champ",
    interim: "Interim",
    poundforpound: "Pound for Pound",
    flyweight: "Flyweight",
    bantamweight: "Bantamweight",
    featherweight: "Featherweight",
    lightweight: "Lightweight",
    welterweight: "Welterweight",
    middleweight: "Middleweight",
    lightheavyweight: "Light Heavyweight",
    heavyweight: "Heavyweight"
  },
  ru: {
    title: "РЕЙТИНГ P4P",
    subtitle: "Фунт за Фунт · Фанатский Рейтинг",
    statVotes: "Голосов", statPi: "Pi Собрано", statPts: "Очков / 1π",
    p4pSec: "Мужской P4P · Рейтинг по голосам фанатов",
    voteFor: "Голосовать за", voteCost: "Стоимость", toFighter: "Бойцу",
    walletNote: "1 Pi переводится в Pi-кошелёк организатора:",
    confirmVote: "ПОДТВЕРДИТЬ — 1π",
    champion: "ЧЕМПИОН", tabP4P: "🏆 P4P ТОП-15",
    toastSuccess: "Голос засчитан за", toastPts: "+100 очков",
    toastError: "Платёж отменён или не прошёл. Попробуйте ещё раз.",
    pts: "очк", loading: "ОБРАБОТКА…",
    disclaimer: "Это фанатский проект, не связанный и не аффилированный ни с одной профессиональной спортивной организацией.",
    p4pOfficialRank: "Официальный ранг",
    votesPrefix: "Голоса:",
    sandboxDemo: "Демо-песочница",
    piBrowser: "Pi Браузер",
    piExclusive: "Эксклюзив Сети Pi",
    limit: "Лимит",
    contender: "Претендент дивизиона",
    ranking: "Рейтинг",
    vote: "Голосовать",
    dualchamp: "Двойной чемпион",
    interim: "Временный",
    poundforpound: "Фунт за фунтом",
    flyweight: "Наилегчайший вес",
    bantamweight: "Легчайший вес",
    featherweight: "Полулегкий вес",
    lightweight: "Легкий вес",
    welterweight: "Полусредний вес",
    middleweight: "Средний вес",
    lightheavyweight: "Полутяжелый вес",
    heavyweight: "Тяжелый вес"
  },
  ar: {
    title: "تصنيف المشجعين P4P",
    subtitle: "باوند فور باوند · تصنيف المشجعين",
    statVotes: "أصوات", statPi: "Pi المُجمَّع", statPts: "نقطة / 1π",
    p4pSec: "P4P الرجال · قائمة أصوات المشجعين",
    voteFor: "صوّت لـ", voteCost: "تكلفة التصويت", toFighter: "للمقاتل",
    walletNote: "يُرسل 1 Pi إلى محفظة المنظّم:",
    confirmVote: "تأكيد التصويت — 1π",
    champion: "البطل", tabP4P: "🏆 أفضل 15 P4P",
    toastSuccess: "تم احتساب صوتك لـ", toastPts: "+100 نقطة",
    toastError: "تم إلغاء الدفع أو فشله. يرجى المحاولة مرة أخرى.",
    pts: "نقطة", loading: "جارٍ المعالجة…",
    disclaimer: "هذا التطبيق مشروع من إعداد المشجعين وليس له أي صلة بأي منظمة رياضية احترافية.",
    p4pOfficialRank: "الترتيب الرسمي",
    votesPrefix: "الأصوات:",
    sandboxDemo: "العرض التجريبي",
    piBrowser: "متصفح Pi",
    piExclusive: "حصري لشبكة Pi",
    limit: "الحد",
    contender: "منافس القسم",
    ranking: "التصنيف",
    vote: "تصويت",
    dualchamp: "بطل مزدوج",
    interim: "مؤقت",
    poundforpound: "باوند فور باوند",
    flyweight: "وزن الذبابة",
    bantamweight: "وزن الديك",
    featherweight: "وزن الريشة",
    lightweight: "الوزن الخفيف",
    welterweight: "وزن الوسط",
    middleweight: "الوزن المتوسط",
    lightheavyweight: "وزن خفيف الثقيل",
    heavyweight: "الوزن الثقيل"
  },
  fr: {
    title: "CLASSEMENT P4P FANS",
    subtitle: "Pound for Pound · Classement des Fans",
    statVotes: "Votes", statPi: "Pi Collectés", statPts: "Points / 1π",
    p4pSec: "P4P Hommes · Classement par votes des fans",
    voteFor: "Voter Pour", voteCost: "Coût du Vote", toFighter: "Au Combattant",
    walletNote: "1 Pi est envoyé au portefeuille Pi de l'organisateur :",
    confirmVote: "CONFIRMER — 1π",
    champion: "CHAMPION", tabP4P: "🏆 P4P TOP-15",
    toastSuccess: "Vote compté pour", toastPts: "+100 pts",
    toastError: "Paiement annulé ou échoué. Veuillez réessayer.",
    pts: "pts", loading: "TRAITEMENT…",
    disclaimer: "Cette application est un projet de fans et n'est affiliée, approuvée ou sponsorisée par aucune organisation sportive professionnelle.",
    p4pOfficialRank: "Rang officiel",
    votesPrefix: "Votes:",
    sandboxDemo: "Démo Sandbox",
    piBrowser: "Navigateur Pi",
    piExclusive: "Exclusivité Pi Network",
    limit: "Limite",
    contender: "Aspirant de Division",
    ranking: "Classement",
    vote: "Voter",
    dualchamp: "Double Champion",
    interim: "Intérimaire",
    poundforpound: "Pound for Pound",
    flyweight: "Poids Mouches",
    bantamweight: "Poids Coqs",
    featherweight: "Poids Plumes",
    lightweight: "Poids Légers",
    welterweight: "Poids Mi-moyens",
    middleweight: "Poids Moyens",
    lightheavyweight: "Poids Mi-lourds",
    heavyweight: "Poids Lourds"
  },
  de: {
    title: "P4P FAN-RANKINGS",
    subtitle: "Pound for Pound · Fan-Rangliste",
    statVotes: "Stimmen", statPi: "Pi Gesammelt", statPts: "Punkte / 1π",
    p4pSec: "Herren P4P · Fan-Stimmen-Rangliste",
    voteFor: "Abstimmen für", voteCost: "Abstimmungskosten", toFighter: "Für Kämpfer",
    walletNote: "1 Pi wird an die Pi-Wallet des Organisators gesendet:",
    confirmVote: "BESTÄTIGEN — 1π",
    champion: "CHAMPION", tabP4P: "🏆 P4P TOP-15",
    toastSuccess: "Stimme gezählt für", toastPts: "+100 Pkt",
    toastError: "Zahlung abgebrochen oder fehlgeschlagen. Bitte erneut versuchen.",
    pts: "Pkt", loading: "VERARBEITUNG…",
    disclaimer: "Diese App ist ein Fan-Projekt und ist weder mit einer professionellen Sportorganisation verbunden noch von ihr gefördert oder gesponsert.",
    p4pOfficialRank: "Offizieller Rang",
    votesPrefix: "Stimmen:",
    sandboxDemo: "Sandbox-Demo",
    piBrowser: "Pi Browser",
    piExclusive: "Pi Network Exklusiv",
    limit: "Limit",
    contender: "Herausforderer",
    ranking: "Rangliste",
    vote: "Abstimmen",
    dualchamp: "Doppel-Champ",
    interim: "Interim",
    poundforpound: "Pound for Pound",
    flyweight: "Fliegengewicht",
    bantamweight: "Bantamgewicht",
    featherweight: "Federgewicht",
    lightweight: "Leichtgewicht",
    welterweight: "Weltergewicht",
    middleweight: "Mittelgewicht",
    lightheavyweight: "Halbschwergewicht",
    heavyweight: "Schwergewicht"
  },
  it: {
    title: "CLASSIFICA FANS P4P",
    subtitle: "Pound for Pound · Classifica Fan",
    statVotes: "Voti", statPi: "Pi Raccolti", statPts: "Punti / 1π",
    p4pSec: "P4P Uomini · Classifica voti dei fan",
    voteFor: "Vota Per", voteCost: "Costo del Voto", toFighter: "Al Combattente",
    walletNote: "1 Pi viene inviato al portafoglio Pi dell'organizzatore:",
    confirmVote: "CONFERMA — 1π",
    champion: "CAMPIONE", tabP4P: "🏆 P4P TOP-15",
    toastSuccess: "Voto contato per", toastPts: "+100 pts",
    toastError: "Pagamento annullato o fallito. Riprova.",
    pts: "pts", loading: "ELABORAZIONE…",
    disclaimer: "Questa app è un progetto di fan e non è affiliata, approvata o sponsorizzata da alcuna organizzazione sportiva professionistica.",
    p4pOfficialRank: "Posizione ufficiale",
    votesPrefix: "Voti:",
    sandboxDemo: "Demo Sandbox",
    piBrowser: "Pi Browser",
    piExclusive: "Esclusiva Pi Network",
    limit: "Limite",
    contender: "Sfidante Divisione",
    ranking: "Posizione",
    vote: "Vota",
    dualchamp: "Doppio Campione",
    interim: "Ad Interim",
    poundforpound: "Pound for Pound",
    flyweight: "Pesi Mosca",
    bantamweight: "Pesi Gallo",
    featherweight: "Pesi Piuma",
    lightweight: "Pesi Leggeri",
    welterweight: "Pesi Welter",
    middleweight: "Pesi Medi",
    lightheavyweight: "Pesi Massimi Leggeri",
    heavyweight: "Pesi Massimi"
  },
  fil: {
    title: "PUNTOS P4P NG MGA FAN",
    subtitle: "Pound for Pound · Fan Rankings",
    statVotes: "Mga Boto", statPi: "Pi Nakolekta", statPts: "Puntos / 1π",
    p4pSec: "P4P Lalaki · Fan Vote Leaderboard",
    voteFor: "Bumoto Para sa", voteCost: "Halaga ng Boto", toFighter: "Para sa Mandirigma",
    walletNote: "1 Pi ay ipinapadala sa Pi wallet ng organizer:",
    confirmVote: "KUMPIRMAHIN — 1π",
    champion: "KAMPEON", tabP4P: "🏆 P4P TOP-15",
    toastSuccess: "Boto nabilang para sa", toastPts: "+100 pts",
    toastError: "Kinansela o nabigo ang bayad. Subukan ulit.",
    pts: "pts", loading: "PINOPROSESO…",
    disclaimer: "Ang app na ito ay isang fan project at hindi kaakibat, inendorso, o sinponsor ng anumang propesyonal na organisasyong pampalakasan.",
    p4pOfficialRank: "Opisyal na ranggo",
    votesPrefix: "Mga Boto:",
    sandboxDemo: "Sandbox Pagsubok",
    piBrowser: "Pi Browser",
    piExclusive: "Eksklusibong Pi Network",
    limit: "Limitasyon",
    contender: "Kabilang sa Division",
    ranking: "Posisyon",
    vote: "Bumoto",
    dualchamp: "Dalawahang Kampeon",
    interim: "Interim",
    poundforpound: "Pound for Pound",
    flyweight: "Flyweight",
    bantamweight: "Bantamweight",
    featherweight: "Featherweight",
    lightweight: "Lightweight",
    welterweight: "Welterweight",
    middleweight: "Middleweight",
    lightheavyweight: "Light Heavyweight",
    heavyweight: "Heavyweight"
  },
  id: {
    title: "PERINGKAT FAN P4P",
    subtitle: "Pound for Pound · Peringkat Penggemar",
    statVotes: "Suara", statPi: "Pi Terkumpul", statPts: "Poin / 1π",
    p4pSec: "P4P Pria · Peringkat Suara Penggemar",
    voteFor: "Pilih", voteCost: "Biaya Suara", toFighter: "Untuk Petarung",
    walletNote: "1 Pi dikirim ke dompet Pi penyelenggara:",
    confirmVote: "KONFIRMASI — 1π",
    champion: "JUARA", tabP4P: "🏆 P4P TOP-15",
    toastSuccess: "Suara dihitung untuk", toastPts: "+100 pts",
    toastError: "Pembayaran dibatalkan atau gagal. Coba lagi.",
    pts: "pts", loading: "MEMPROSES…",
    disclaimer: "Aplikasi ini adalah proyek penggemar dan tidak berafiliasi, didukung, atau disponsori oleh organisasi olahraga profesional mana pun.",
    p4pOfficialRank: "Peringkat resmi",
    votesPrefix: "Suara:",
    sandboxDemo: "Demo Sandbox",
    piBrowser: "Browser Pi",
    piExclusive: "Eksklusif Pi Network",
    limit: "Batas",
    contender: "Penantang Divisi",
    ranking: "Peringkat",
    vote: "Pilih",
    dualchamp: "Juara Ganda",
    interim: "Interim",
    poundforpound: "Pound for Pound",
    flyweight: "Kelas Terbang",
    bantamweight: "Kelas Bantam",
    featherweight: "Kelas Bulu",
    lightweight: "Kelas Ringan",
    welterweight: "Kelas Welter",
    middleweight: "Kelas Menengah",
    lightheavyweight: "Kelas Berat Ringan",
    heavyweight: "Kelas Berat"
  },
  zh: {
    title: "P4P 粉丝排行榜",
    subtitle: "磅磅制 · 球迷排行榜",
    statVotes: "投票数", statPi: "已收Pi", statPts: "积分 / 1π",
    p4pSec: "男子P4P · 球迷投票排行榜",
    voteFor: "投票给", voteCost: "投票费用", toFighter: "给选手",
    walletNote: "1 Pi 将发送至主办方的Pi钱包：",
    confirmVote: "确认投票 — 1π",
    champion: "冠军", tabP4P: "🏆 P4P 前15名",
    toastSuccess: "投票成功", toastPts: "+100分",
    toastError: "付款已取消或失败，请重试。",
    pts: "分", loading: "处理中…",
    disclaimer: "本应用程序为球迷自发项目，与任何职业体育组织无任何关联、背书或赞助关系。",
    p4pOfficialRank: "官方排名",
    votesPrefix: "得票数:",
    sandboxDemo: "沙盒演示",
    piBrowser: "Pi 浏览器",
    piExclusive: "Pi Network 独家",
    limit: "限制",
    contender: "级别挑战者",
    ranking: "排名",
    vote: "投票",
    dualchamp: "双冠王",
    interim: "临时",
    poundforpound: "磅磅制",
    flyweight: "蝇量级",
    bantamweight: "雏量级",
    featherweight: "羽量级",
    lightweight: "轻量级",
    welterweight: "次中量级",
    middleweight: "中量级",
    lightheavyweight: "轻重量级",
    heavyweight: "重量级"
  },
  ja: {
    title: "P4P ファンランキング",
    subtitle: "パウンド・フォー・パウンド · ファンランキング",
    statVotes: "投票数", statPi: "Pi収集", statPts: "ポイント / 1π",
    p4pSec: "男子P4P · ファン投票ランキング",
    voteFor: "投票する", voteCost: "投票コスト", toFighter: "選手に",
    walletNote: "1 Piは主催者のPiウォレットに送信されます：",
    confirmVote: "投票を確認 — 1π",
    champion: "チャンピオン", tabP4P: "🏆 P4P TOP-15",
    toastSuccess: "投票が記録されました", toastPts: "+100pt",
    toastError: "支払いがキャンセルまたは失敗しました。もう一度お試しください。",
    pts: "pt", loading: "処理中…",
    disclaimer: "このアプリはファンプロジェクトであり、いかなるプロスポーツ組織とも提携、推薦、スポンサー関係にありません。",
    p4pOfficialRank: "公式ランク",
    votesPrefix: "投票数:",
    sandboxDemo: "サンドボックスデモ",
    piBrowser: "Pi ブラウザ",
    piExclusive: "Pi Network 限定",
    limit: "制限",
    contender: "階級コンテンダー",
    ranking: "順位",
    vote: "投票",
    dualchamp: "同時2階級制覇王者",
    interim: "暫定",
    poundforpound: "パウンド・フォー・パウンド",
    flyweight: "フライ級",
    bantamweight: "バンタム級",
    featherweight: "フェザー級",
    lightweight: "ライト級",
    welterweight: "ウェルター級",
    middleweight: "ミドル級",
    lightheavyweight: "ライトヘビー級",
    heavyweight: "ヘビー級"
  },
  ko: {
    title: "P4P 팬 랭킹",
    subtitle: "파운드 포 파운드 · 팬 랭킹",
    statVotes: "투표 수", statPi: "Pi 수집", statPts: "포인트 / 1π",
    p4pSec: "남자 P4P · 팬 투표 리더보드",
    voteFor: "투표하기", voteCost: "투표 비용", toFighter: "선수에게",
    walletNote: "1 Pi는 주최자의 Pi 지갑으로 전송됩니다:",
    confirmVote: "투표 확인 — 1π",
    champion: "챔피언", tabP4P: "🏆 P4P TOP-15",
    toastSuccess: "투표 완료", toastPts: "+100pt",
    toastError: "결제가 취소되었거나 실패했습니다. 다시 시도해 주세요.",
    pts: "pt", loading: "처리 중…",
    disclaimer: "이 앱은 팬 프로젝트이며 어떠한 전문 스포츠 기관과도 제휴, 보증 또는 후원 관계가 없습니다.",
    p4pOfficialRank: "공식 순위",
    votesPrefix: "득표:",
    sandboxDemo: "샌드박스 데모",
    piBrowser: "Pi 브라우저",
    piExclusive: "Pi Network 독점",
    limit: "체중 제한",
    contender: "디비전 컨텐더",
    ranking: "순위",
    vote: "투표",
    dualchamp: "두 체급 챔피언",
    interim: "잠정",
    poundforpound: "파운드 포 파운드",
    flyweight: "플라이급",
    bantamweight: "밴텀급",
    featherweight: "페더급",
    lightweight: "라이트급",
    welterweight: "웰터급",
    middleweight: "미들급",
    lightheavyweight: "라이트헤비급",
    heavyweight: "헤비급"
  }
};

export const P4P_LIST: Fighter[] = [
  { name: 'Islam Makhachev', flag: '🇷🇺', div: 'Welterweight / Lightweight', record: '28-1' },
  { name: 'Ilia Topuria', flag: '🇬🇪', div: 'Lightweight / Featherweight', record: '17-0' },
  { name: 'Alex Pereira', flag: '🇧🇷', div: 'Light Heavyweight', record: '12-2' },
  { name: 'Alexander Volkanovski', flag: '🇦🇺', div: 'Featherweight', record: '26-3' },
  { name: 'Petr Yan', flag: '🇷🇺', div: 'Bantamweight', record: '17-5' },
  { name: 'Joshua Van', flag: '🇦🇺', div: 'Flyweight', record: '15-3' },
  { name: 'Khamzat Chimaev', flag: '🇸🇪', div: 'Middleweight', record: '15-1' },
  { name: 'Tom Aspinall', flag: '🇬🇧', div: 'Heavyweight', record: '15-3' },
  { name: 'Sean Strickland', flag: '🇺🇸', div: 'Middleweight', record: '31-7' },
  { name: 'Alexandre Pantoja', flag: '🇧🇷', div: 'Flyweight', record: '30-5' },
  { name: 'Arman Tsarukyan', flag: '🇦🇲', div: 'Lightweight', record: '23-3' },
  { name: 'Dricus Du Plessis', flag: '🇿🇦', div: 'Middleweight', record: '23-3' },
  { name: 'Carlos Ulberg', flag: '🇳🇿', div: 'Light Heavyweight', record: '14-1' },
  { name: 'Merab Dvalishvili', flag: '🇬🇪', div: 'Bantamweight', record: '18-4' },
  { name: 'Justin Gaethje', flag: '🇺🇸', div: 'Lightweight', record: '27-5' },
];

export const WEIGHT_CLASSES: WeightClass[] = [
  {
    id: 'flyweight', icon: '⚡',
    label: 'FLYWEIGHT', limit: '125 lb / 56.7 kg',
    champ: { name: 'Joshua Van', flag: '🇦🇺', record: '14-3' },
    fighters: [
      { rank: 1, name: 'Alexandre Pantoja', flag: '🇧🇷', record: '30-5' },
      { rank: 2, name: 'Manel Kape', flag: '🇦🇴', record: '19-7' },
      { rank: 3, name: 'Tatsuro Taira', flag: '🇯🇵', record: '16-0' },
      { rank: 4, name: 'Brandon Royval', flag: '🇺🇸', record: '16-8' },
      { rank: 5, name: 'Kyoji Horiguchi', flag: '🇯🇵', record: '32-5' },
      { rank: 6, name: "Lone'er Kavanagh", flag: '🇩🇰', record: '14-3' },
      { rank: 7, name: 'Amir Albazi', flag: '🇸🇪', record: '18-3' },
      { rank: 8, name: 'Asu Almabayev', flag: '🇰🇿', record: '14-2' },
      { rank: 9, name: 'Brandon Moreno', flag: '🇲🇽', record: '22-7-1' },
      { rank: 10, name: 'Alex Perez', flag: '🇺🇸', record: '12-5' },
      { rank: 11, name: 'Tim Elliott', flag: '🇺🇸', record: '19-13-1' },
      { rank: 12, name: 'Steve Erceg', flag: '🇦🇺', record: '13-3' },
      { rank: 13, name: 'Charles Johnson', flag: '🇺🇸', record: '16-5' },
      { rank: 14, name: 'Tagir Ulanbekov', flag: '🇷🇺', record: '15-3' },
      { rank: 15, name: 'Bruno Silva', flag: '🇧🇷', record: '24-11' },
    ]
  },
  {
    id: 'bantamweight', icon: '🥊',
    label: 'BANTAMWEIGHT', limit: '135 lb / 61.2 kg',
    champ: { name: 'Petr Yan', flag: '🇷🇺', record: '17-5' },
    fighters: [
      { rank: 1, name: 'Merab Dvalishvili', flag: '🇬🇪', record: '18-4' },
      { rank: 2, name: 'Umar Nurmagomedov', flag: '🇷🇺', record: '18-0' },
      { rank: 3, name: "Sean O'Malley", flag: '🇺🇸', record: '18-2' },
      { rank: 4, name: 'Cory Sandhagen', flag: '🇺🇸', record: '17-5' },
      { rank: 5, name: 'Song Yadong', flag: '🇨🇳', record: '22-8-1' },
      { rank: 6, name: 'Aiemann Zahabi', flag: '🇨🇦', record: '18-3' },
      { rank: 7, name: 'Deiveson Figueiredo', flag: '🇧🇷', record: '23-4-1' },
      { rank: 8, name: 'Mario Bautista', flag: '🇺🇸', record: '14-3' },
      { rank: 9, name: 'David Martinez', flag: '🇪🇸', record: '14-3' },
      { rank: 10, name: 'Marlon Vera', flag: '🇪🇨', record: '23-10' },
      { rank: 11, name: 'Payton Talbott', flag: '🇺🇸', record: '12-2' },
      { rank: 12, name: 'Vinicius Oliveira', flag: '🇧🇷', record: '23-4' },
      { rank: 13, name: 'Raul Rosas Jr.', flag: '🇲🇽', record: '12-3' },
      { rank: 14, name: 'Montel Jackson', flag: '🇺🇸', record: '16-7' },
      { rank: 15, name: 'Farid Basharat', flag: '🇦🇫', record: '16-1' },
    ]
  },
  {
    id: 'featherweight', icon: '🦅',
    label: 'FEATHERWEIGHT', limit: '145 lb / 65.8 kg',
    champ: { name: 'Alexander Volkanovski', flag: '🇦🇺', record: '26-3' },
    fighters: [
      { rank: 1, name: 'Movsar Evloev', flag: '🇷🇺', record: '18-0' },
      { rank: 2, name: 'Diego Lopes', flag: '🇧🇷', record: '25-7' },
      { rank: 3, name: 'Lerone Murphy', flag: '🇬🇧', record: '15-0-1' },
      { rank: 4, name: 'Yair Rodriguez', flag: '🇲🇽', record: '16-5' },
      { rank: 5, name: 'Aljamain Sterling', flag: '🇺🇸', record: '24-5' },
      { rank: 6, name: 'Jean Silva', flag: '🇧🇷', record: '14-2' },
      { rank: 7, name: 'Youssef Zalal', flag: '🇲🇦', record: '19-7' },
      { rank: 8, name: 'Arnold Allen', flag: '🇬🇧', record: '19-2' },
      { rank: 9, name: 'Steve Garcia', flag: '🇺🇸', record: '16-7' },
      { rank: 10, name: 'Kevin Vallejos', flag: '🇺🇾', record: '14-4' },
      { rank: 11, name: 'Brian Ortega', flag: '🇺🇸', record: '16-4' },
      { rank: 12, name: 'Melquizael Costa', flag: '🇧🇷', record: '16-3' },
      { rank: 13, name: 'Aaron Pico', flag: '🇺🇸', record: '11-4' },
      { rank: 14, name: 'David Onama', flag: '🇺🇬', record: '16-5' },
      { rank: 15, name: 'Patricio Pitbull', flag: '🇧🇷', record: '35-5' },
    ]
  },
  {
    id: 'lightweight', icon: '💨',
    label: 'LIGHTWEIGHT', limit: '155 lb / 70.3 kg',
    champ: { name: 'Ilia Topuria', flag: '🇬🇪', record: '17-0' },
    fighters: [
      { rank: 1, name: 'Justin Gaethje', flag: '🇺🇸', record: '27-5', note: 'Interim' },
      { rank: 2, name: 'Arman Tsarukyan', flag: '🇦🇲', record: '23-3' },
      { rank: 3, name: 'Charles Oliveira', flag: '🇧🇷', record: '37-11' },
      { rank: 4, name: 'Max Holloway', flag: '🇺🇸', record: '27-9' },
      { rank: 5, name: 'Benoît Saint Denis', flag: '🇫🇷', record: '17-3' },
      { rank: 6, name: 'Paddy Pimblett', flag: '🇬🇧', record: '23-4' },
      { rank: 7, name: 'Mateusz Gamrot', flag: '🇵🇱', record: '26-4' },
      { rank: 8, name: 'Dan Hooker', flag: '🇳🇿', record: '24-14' },
      { rank: 9, name: 'Renato Moicano', flag: '🇧🇷', record: '21-6-1' },
      { rank: 10, name: 'Mauricio Ruffy', flag: '🇧🇷', record: '13-0' },
      { rank: 11, name: 'Rafael Fiziev', flag: '🇰🇿', record: '15-4' },
      { rank: 12, name: 'Beneil Dariush', flag: '🇺🇸', record: '22-5-1' },
      { rank: 13, name: 'Michael Chandler', flag: '🇺🇸', record: '23-9' },
      { rank: 14, name: 'Manuel Torres', flag: '🇲🇽', record: '18-3' },
      { rank: 15, name: 'Farès Ziam', flag: '🇫🇷', record: '17-6' },
    ]
  },
  {
    id: 'welterweight', icon: '💪',
    label: 'WELTERWEIGHT', limit: '170 lb / 77.1 kg',
    champ: { name: 'Islam Makhachev', flag: '🇷🇺', record: '28-1', note: 'Dual Champ' },
    fighters: [
      { rank: 1, name: 'Ian Machado Garry', flag: '🇮🇪', record: '17-1' },
      { rank: 2, name: 'Carlos Prates', flag: '🇧🇷', record: '24-7' },
      { rank: 3, name: 'Michael Morales', flag: '🇪🇨', record: '19-0' },
      { rank: 4, name: 'Jack Della Maddalena', flag: '🇦🇺', record: '18-4' },
      { rank: 5, name: 'Belal Muhammad', flag: '🇺🇸', record: '24-5' },
      { rank: 6, name: 'Sean Brady', flag: '🇺🇸', record: '19-2' },
      { rank: 7, name: 'Leon Edwards', flag: '🇬🇧', record: '22-6' },
      { rank: 8, name: 'Kamaru Usman', flag: '🇳🇬', record: '21-4' },
      { rank: 9, name: 'Joaquin Buckley', flag: '🇺🇸', record: '21-8' },
      { rank: 10, name: 'Rafael Bonfim', flag: '🇧🇷', record: '19-1' },
      { rank: 11, name: 'Gilbert Burns', flag: '🇧🇷', record: '23-7' },
      { rank: 12, name: 'Michael Venom Page', flag: '🇬🇧', record: '22-4' },
      { rank: 13, name: 'Uroš Medić', flag: '🇷🇸', record: '16-3' },
      { rank: 14, name: 'Daniel Rodriguez', flag: '🇺🇸', record: '18-5' },
      { rank: 15, name: 'Colby Covington', flag: '🇺🇸', record: '17-5' },
    ]
  },
  {
    id: 'middleweight', icon: '🔥',
    label: 'MIDDLEWEIGHT', limit: '185 lb / 83.9 kg',
    champ: { name: 'Sean Strickland', flag: '🇺🇸', record: '31-7' },
    fighters: [
      { rank: 1, name: 'Dricus Du Plessis', flag: '🇿🇦', record: '23-3' },
      { rank: 2, name: 'Nassourdine Imavov', flag: '🇷🇺', record: '17-4' },
      { rank: 3, name: 'Khamzat Chimaev', flag: '🇸🇪', record: '15-1' },
      { rank: 4, name: 'Caio Borralho', flag: '🇧🇷', record: '18-2' },
      { rank: 5, name: 'Robert Whittaker', flag: '🇦🇺', record: '26-9' },
      { rank: 6, name: 'Joe Pyfer', flag: '🇺🇸', record: '16-3' },
      { rank: 7, name: 'Brendan Allen', flag: '🇺🇸', record: '24-6' },
      { rank: 8, name: 'Reinier de Ridder', flag: '🇳🇱', record: '21-4' },
      { rank: 9, name: 'Israel Adesanya', flag: '🇳🇿', record: '24-6' },
      { rank: 10, name: 'Michel Pereira', flag: '🇧🇷', record: '31-12' },
      { rank: 11, name: 'Jared Cannonier', flag: '🇺🇸', record: '18-9' },
      { rank: 12, name: 'Bo Nickal', flag: '🇺🇸', record: '9-0' },
      { rank: 13, name: 'Paulo Costa', flag: '🇧🇷', record: '16-4' },
      { rank: 14, name: 'Abus Magomedov', flag: '🇷🇺', record: '28-5' },
      { rank: 15, name: 'Chris Curtis', flag: '🇺🇸', record: '26-7' },
    ]
  },
  {
    id: 'lightheavyweight', icon: '🦁',
    label: 'LIGHT HEAVYWEIGHT', limit: '205 lb / 92.9 kg',
    champ: { name: 'Carlos Ulberg', flag: '🇳🇿', record: '13-1' },
    fighters: [
      { rank: 1, name: 'Magomed Ankalaev', flag: '🇷🇺', record: '19-1-1' },
      { rank: 2, name: 'Jiří Procházka', flag: '🇨🇿', record: '30-5-1' },
      { rank: 3, name: 'Alex Pereira', flag: '🇧🇷', record: '11-2' },
      { rank: 4, name: 'Aleksandar Rakić', flag: '🇦🇹', record: '16-4' },
      { rank: 5, name: 'Jamahal Hill', flag: '🇺🇸', record: '13-3' },
      { rank: 6, name: 'Paulo Costa', flag: '🇧🇷', record: '15-4' },
      { rank: 7, name: 'Azamat Murzakanov', flag: '🇷🇺', record: '13-2' },
      { rank: 8, name: 'Dominick Reyes', flag: '🇺🇸', record: '15-5' },
      { rank: 9, name: 'Johnny Walker', flag: '🇧🇷', record: '23-8' },
      { rank: 10, name: 'Volkan Oezdemir', flag: '🇨🇭', record: '19-7' },
      { rank: 11, name: 'Khalil Rountree Jr.', flag: '🇺🇸', record: '14-5' },
      { rank: 12, name: 'Anthony Smith', flag: '🇺🇸', record: '37-18' },
      { rank: 13, name: 'Ovince Saint Preux', flag: '🇺🇸', record: '29-16' },
      { rank: 14, name: 'Ryan Spann', flag: '🇺🇸', record: '21-10' },
      { rank: 15, name: 'Nikita Krylov', flag: '🇺🇦', record: '29-9' },
    ]
  },
  {
    id: 'heavyweight', icon: '🏔️',
    label: 'HEAVYWEIGHT', limit: '265 lb / 120.2 kg',
    champ: { name: 'Tom Aspinall', flag: '🇬🇧', record: '15-3' },
    fighters: [
      { rank: 1, name: 'Ciryl Gane', flag: '🇫🇷', record: '13-2' },
      { rank: 2, name: 'Alexander Volkov', flag: '🇷🇺', record: '40-11' },
      { rank: 3, name: 'Sergei Pavlovich', flag: '🇷🇺', record: '20-3' },
      { rank: 4, name: 'Jailton Almeida', flag: '🇧🇷', record: '22-3' },
      { rank: 5, name: 'Josh Hokit', flag: '🇺🇸', record: '9-0' },
      { rank: 6, name: 'Sergei Spivac', flag: '🇲🇩', record: '18-6' },
      { rank: 7, name: 'Curtis Blaydes', flag: '🇺🇸', record: '19-6' },
      { rank: 8, name: 'Tai Tuivasa', flag: '🇦🇺', record: '15-7' },
      { rank: 9, name: 'Derrick Lewis', flag: '🇺🇸', record: '26-13' },
      { rank: 10, name: 'Marcin Tybura', flag: '🇵🇱', record: '25-8' },
      { rank: 11, name: 'Shamil Gaziev', flag: '🇷🇺', record: '12-1' },
      { rank: 12, name: 'Rodrigo Nascimento', flag: '🇧🇷', record: '15-1' },
      { rank: 13, name: 'Alexandr Romanov', flag: '🇲🇩', record: '17-4' },
      { rank: 14, name: 'Ben Rothwell', flag: '🇺🇸', record: '39-14' },
      { rank: 15, name: 'Greg Hardy', flag: '🇺🇸', record: '7-8' },
    ]
  }
];

export const PHOTOS: Record<string, string> = {
  'Islam Makhachev': 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/84/Islam_Makhachev_%28cropped%29.jpg/200px-Islam_Makhachev_%28cropped%29.jpg',
  'Ilia Topuria': 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e8/Ilia_Topuria_at_UFC_296_Open_Workouts_%28cropped%29.jpg/200px-Ilia_Topuria_at_UFC_296_Open_Workouts_%28cropped%29.jpg',
  'Khamzat Chimaev': 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/19/Khamzat_Chimaev_UFC_267_Open_Workouts_%28cropped%29.jpg/200px-Khamzat_Chimaev_UFC_267_Open_Workouts_%28cropped%29.jpg',
  'Alexander Volkanovski': 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a8/Alexander_Volkanovski_UFC_284_Open_Workouts_%28cropped%29.jpg/200px-Alexander_Volkanovski_UFC_284_Open_Workouts_%28cropped%29.jpg',
  'Alex Pereira': 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/42/Alex_Pereira_UFC_281_Open_Workouts_%28cropped%29.jpg/200px-Alex_Pereira_UFC_281_Open_Workouts_%28cropped%29.jpg',
  'Petr Yan': 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a0/Petr_Yan_UFC_267_Open_Workouts_%28cropped%29.jpg/200px-Petr_Yan_UFC_267_Open_Workouts_%28cropped%29.jpg',
  'Tom Aspinall': 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/48/Tom_Aspinall_UFC_Fight_Night_204_Open_Workouts_%28cropped%29.jpg/200px-Tom_Aspinall_UFC_Fight_Night_204_Open_Workouts_%28cropped%29.jpg',
  'Merab Dvalishvili': 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/70/Merab_Dvalishvili_UFC_Fight_Night_212_Open_Workouts_%28cropped%29.jpg/200px-Merab_Dvalishvili_UFC_Fight_Night_212_Open_Workouts_%28cropped%29.jpg',
  'Alexandre Pantoja': 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/1b/Alexandre_Pantoja_UFC_301_Open_Workouts_%28cropped%29.jpg/200px-Alexandre_Pantoja_UFC_301_Open_Workouts_%28cropped%29.jpg',
  'Joshua Van': 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/30/Joshua_Van_UFC_Fight_Night_232_Open_Workouts_%28cropped%29.jpg/200px-Joshua_Van_UFC_Fight_Night_232_Open_Workouts_%28cropped%29.jpg',
  'Charles Oliveira': 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b7/Charles_Oliveira_UFC_280_Open_Workouts_%28cropped%29.jpg/200px-Charles_Oliveira_UFC_280_Open_Workouts_%28cropped%29.jpg',
  'Dricus Du Plessis': 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/63/Dricus_Du_Plessis_UFC_Fight_Night_212_Open_Workouts_%28cropped%29.jpg/200px-Dricus_Du_Plessis_UFC_Fight_Night_212_Open_Workouts_%28cropped%29.jpg',
  'Arman Tsarukyan': 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5d/Arman_Tsarukyan_UFC_Fight_Night_223_Open_Workouts_%28cropped%29.jpg/200px-Arman_Tsarukyan_UFC_Fight_Night_223_Open_Workouts_%28cropped%29.jpg',
  'Magomed Ankalaev': 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e1/Magomed_Ankalaev_UFC_267_Open_Workouts_%28cropped%29.jpg/200px-Magomed_Ankalaev_UFC_267_Open_Workouts_%28cropped%29.jpg',
  'Carlos Ulberg': 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/55/Carlos_Ulberg_UFC_Fight_Night_225_Open_Workouts_%28cropped%29.jpg/200px-Carlos_Ulberg_UFC_Fight_Night_225_Open_Workouts_%28cropped%29.jpg',
  'Manel Kape': 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4d/Manel_Kape_UFC_Fight_Night_196_Open_Workouts_%28cropped%29.jpg/200px-Manel_Kape_UFC_Fight_Night_196_Open_Workouts_%28cropped%29.jpg',
  'Brandon Moreno': 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/60/Brandon_Moreno_UFC_277_Open_Workouts_%28cropped%29.jpg/200px-Brandon_Moreno_UFC_277_Open_Workouts_%28cropped%29.jpg',
  'Amir Albazi': 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/54/Amir_Albazi_UFC_Fight_Night_220_Open_Workouts_%28cropped%29.jpg/200px-Amir_Albazi_UFC_Fight_Night_220_Open_Workouts_%28cropped%29.jpg',
  'Umar Nurmagomedov': 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e4/Umar_Nurmagomedov_UFC_Fight_Night_228_Open_Workouts_%28cropped%29.jpg/200px-Umar_Nurmagomedov_UFC_Fight_Night_228_Open_Workouts_%28cropped%29.jpg',
  "Sean O'Malley": 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/7e/Sean_O%27Malley_UFC_292_Open_Workouts_%28cropped%29.jpg/200px-Sean_O%27Malley_UFC_292_Open_Workouts_%28cropped%29.jpg',
  'Cory Sandhagen': 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2e/Cory_Sandhagen_UFC_Fight_Night_180_Open_Workouts_%28cropped%29.jpg/200px-Cory_Sandhagen_UFC_Fight_Night_180_Open_Workouts_%28cropped%29.jpg',
  'Deiveson Figueiredo': 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/ee/Deiveson_Figueiredo_UFC_Fight_Night_189_Open_Workouts_%28cropped%29.jpg/200px-Deiveson_Figueiredo_UFC_Fight_Night_189_Open_Workouts_%28cropped%29.jpg',
  'Marlon Vera': 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/82/Marlon_Vera_UFC_Fight_Night_185_Open_Workouts_%28cropped%29.jpg/200px-Marlon_Vera_UFC_Fight_Night_185_Open_Workouts_%28cropped%29.jpg',
  'Movsar Evloev': 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f4/Movsar_Evloev_UFC_Fight_Night_224_Open_Workouts_%28cropped%29.jpg/200px-Movsar_Evloev_UFC_Fight_Night_224_Open_Workouts_%28cropped%29.jpg',
  'Diego Lopes': 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/36/Diego_Lopes_UFC_Fight_Night_234_Open_Workouts_%28cropped%29.jpg/200px-Diego_Lopes_UFC_Fight_Night_234_Open_Workouts_%28cropped%29.jpg',
  'Aljamain Sterling': 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/47/Aljamain_Sterling_UFC_Fight_Night_185_Open_Workouts_%28cropped%29.jpg/200px-Aljamain_Sterling_UFC_Fight_Night_185_Open_Workouts_%28cropped%29.jpg',
  'Max Holloway': 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e5/Max_Holloway_UFC_300_Open_Workouts_%28cropped%29.jpg/200px-Max_Holloway_UFC_300_Open_Workouts_%28cropped%29.jpg',
  'Yair Rodriguez': 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/38/Yair_Rodriguez_UFC_Fight_Night_228_Open_Workouts_%28cropped%29.jpg/200px-Yair_Rodriguez_UFC_Fight_Night_228_Open_Workouts_%28cropped%29.jpg',
  'Brian Ortega': 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d9/Brian_Ortega_UFC_266_Open_Workouts_%28cropped%29.jpg/200px-Brian_Ortega_UFC_266_Open_Workouts_%28cropped%29.jpg',
  'Justin Gaethje': 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/07/Justin_Gaethje_UFC_291_Open_Workouts_%28cropped%29.jpg/200px-Justin_Gaethje_UFC_291_Open_Workouts_%28cropped%29.jpg',
  'Paddy Pimblett': 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/88/Paddy_Pimblett_UFC_Fight_Night_204_Open_Workouts_%28cropped%29.jpg/200px-Paddy_Pimblett_UFC_Fight_Night_204_Open_Workouts_%28cropped%29.jpg',
  'Michael Chandler': 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a6/Michael_Chandler_UFC_274_Open_Workouts_%28cropped%29.jpg/200px-Michael_Chandler_UFC_274_Open_Workouts_%28cropped%29.jpg',
  'Beneil Dariush': 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/68/Beneil_Dariush_UFC_Fight_Night_207_Open_Workouts_%28cropped%29.jpg/200px-Beneil_Dariush_UFC_Fight_Night_207_Open_Workouts_%28cropped%29.jpg',
  'Jack Della Maddalena': 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/04/Jack_Della_Maddalena_UFC_Fight_Night_234_Open_Workouts_%28cropped%29.jpg/200px-Jack_Della_Maddalena_UFC_Fight_Night_234_Open_Workouts_%28cropped%29.jpg',
  'Ian Machado Garry': 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5a/Ian_Machado_Garry_UFC_Fight_Night_220_Open_Workouts_%28cropped%29.jpg/200px-Ian_Machado_Garry_UFC_Fight_Night_220_Open_Workouts_%28cropped%29.jpg',
  'Belal Muhammad': 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/1d/Belal_Muhammad_UFC_Fight_Night_207_Open_Workouts_%28cropped%29.jpg/200px-Belal_Muhammad_UFC_Fight_Night_207_Open_Workouts_%28cropped%29.jpg',
  'Kamaru Usman': 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e9/Kamaru_Usman_UFC_278_Open_Workouts_%28cropped%29.jpg/200px-Kamaru_Usman_UFC_278_Open_Workouts_%28cropped%29.jpg',
  'Leon Edwards': 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e4/Leon_Edwards_UFC_Fight_Night_204_Open_Workouts_%28cropped%29.jpg/200px-Leon_Edwards_UFC_Fight_Night_204_Open_Workouts_%28cropped%29.jpg',
  'Colby Covington': 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/13/Colby_Covington_UFC_Fight_Night_179_Open_Workouts_%28cropped%29.jpg/200px-Colby_Covington_UFC_Fight_Night_179_Open_Workouts_%28cropped%29.jpg',
  'Sean Strickland': 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9a/Sean_Strickland_UFC_297_Open_Workouts_%28cropped%29.jpg/200px-Sean_Strickland_UFC_297_Open_Workouts_%28cropped%29.jpg',
  'Robert Whittaker': 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c2/Robert_Whittaker_UFC_Fight_Night_193_Open_Workouts_%28cropped%29.jpg/200px-Robert_Whittaker_UFC_Fight_Night_193_Open_Workouts_%28cropped%29.jpg',
  'Paulo Costa': 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/bd/Paulo_Costa_UFC_278_Open_Workouts_%28cropped%29.jpg/200px-Paulo_Costa_UFC_278_Open_Workouts_%28cropped%29.jpg',
  'Marvin Vettori': 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5e/Marvin_Vettori_UFC_Fight_Night_185_Open_Workouts_%28cropped%29.jpg/200px-Marvin_Vettori_UFC_Fight_Night_185_Open_Workouts_%28cropped%29.jpg',
  'Bo Nickal': 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b2/Bo_Nickal_UFC_Fight_Night_220_Open_Workouts_%28cropped%29.jpg/200px-Bo_Nickal_UFC_Fight_Night_220_Open_Workouts_%28cropped%29.jpg',
  'Jiří Procházka': 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d4/Jiri_Prochazka_UFC_275_Open_Workouts_%28cropped%29.jpg/200px-Jiri_Prochazka_UFC_275_Open_Workouts_%28cropped%29.jpg',
  'Jamahal Hill': 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5b/Jamahal_Hill_UFC_Fight_Night_216_Open_Workouts_%28cropped%29.jpg/200px-Jamahal_Hill_UFC_Fight_Night_216_Open_Workouts_%28cropped%29.jpg',
  'Aleksandar Rakić': 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/79/Aleksandar_Raki%C4%87_UFC_Fight_Night_192_Open_Workouts_%28cropped%29.jpg/200px-Aleksandar_Raki%C4%87_UFC_Fight_Night_192_Open_Workouts_%28cropped%29.jpg',
  'Anthony Smith': 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/82/Anthony_Smith_UFC_Fight_Night_180_Open_Workouts_%28cropped%29.jpg/200px-Anthony_Smith_UFC_Fight_Night_180_Open_Workouts_%28cropped%29.jpg',
  'Jon Jones': 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/57/Jon_Jones_UFC_285_Open_Workouts_%28cropped%29.jpg/200px-Jon_Jones_UFC_285_Open_Workouts_%28cropped%29.jpg',
  'Stipe Miocic': 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/00/Stipe_Miocic_UFC_309_Open_Workouts_%28cropped%29.jpg/200px-Stipe_Miocic_UFC_309_Open_Workouts_%28cropped%29.jpg',
  'Ciryl Gane': 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/ce/Ciryl_Gane_UFC_Fight_Night_204_Open_Workouts_%28cropped%29.jpg/200px-Ciryl_Gane_UFC_Fight_Night_204_Open_Workouts_%28cropped%29.jpg',
  'Curtis Blaydes': 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9e/Curtis_Blaydes_UFC_Fight_Night_204_Open_Workouts_%28cropped%29.jpg/200px-Curtis_Blaydes_UFC_Fight_Night_204_Open_Workouts_%28cropped%29.jpg',
  'Jailton Almeida': 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/19/Jailton_Almeida_UFC_Fight_Night_220_Open_Workouts_%28cropped%29.jpg/200px-Jailton_Almeida_UFC_Fight_Night_220_Open_Workouts_%28cropped%29.jpg',
  'Derrick Lewis': 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/10/Derrick_Lewis_UFC_Fight_Night_180_Open_Workouts_%28cropped%29.jpg/200px-Derrick_Lewis_UFC_Fight_Night_180_Open_Workouts_%28cropped%29.jpg',
};
